[package]
name = "http-server"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
publish = false

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
proxy = true

[dependencies]
waki = "0.4.0"

# reduce wasm binary size
[profile.release]
lto = true
strip = "symbols"
