[package]
name = "test-programs-artifacts"
version = "0.0.0"
edition = "2021"
publish = false

[build-dependencies]
anyhow.workspace = true
cargo_metadata = "0.18.1"
wit-component = "0.219.1"
heck = "0.5.0"
wasi-preview1-component-adapter-provider = "25.0.1"
version_check = "0.9.5"
